// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

function Index$Example(Props) {
  return React.createElement("div", undefined, "Hello");
}

var Example = /* module */[/* make */Index$Example];

ReactDOMRe.renderToElementWithId(React.createElement(Index$Example, { }), "root");

exports.Example = Example;
/*  Not a pure module */
